# Generated by Django 5.1.5 on 2025-02-10 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_category_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Category',
            new_name='category',
        ),
    ]
